#!/bin/sh

fn_start()
{
 #must start after module 1
 grep 'module1 start' /tmp/nnnatesttr >/dev/null 2>&1
 if [ "$?" -ne '0' ]; then
  echo "ERROR" >>/tmp/nnnatesttr
 fi
 echo 'module3 start' >>/tmp/nnnatesttr
 return 0
}

fn_status()
{
 grep 'module3 stop' /tmp/nnnatesttr >/dev/null 2>&1
 [ "$?" -eq '0' ] && return 3
 return 0
}

fn_stop()
{
#must be stop before module 1
 grep 'module1 stop' /tmp/nnnatesttr >/dev/null 2>&1
 if [ "$?" -ne '0' ]; then
  echo "ERROR" >>/tmp/nnnatesttr
 fi
 echo "module3 stop" >>/tmp/nnnatesttr
 return 0
}
